<h1>2D <code>Numpy</code> in Python</h1>

<p><strong>Welcome!</strong> This notebook will teach you about using <code>Numpy</code> in the Python Programming Language. By the end of this lab, you'll know what <code>Numpy</code> is and the <code>Numpy</code> operations.</p>

# Create a 2D Numpy Array

In [1]:
# Import the libraries
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Consider the list a, the list contains three nested lists each of equal size.
# Create a list

a=[[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# We can cast the list to numpy array as follows:
# Every element is the same type

A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
# show the np array dimensions
A.ndim

2

In [5]:
# show the numpy array shape 
A.shape

(3, 3)

In [8]:
# Show the numpy array size
A.size

9

# Accessing different elements of a Numpy Array

In [10]:
# access the element of the second row and the third column of the array 

A[1,2]

23

In [11]:
A[1][2]

23

In [12]:
# Access the element of the first row and the first column
A[0][0]

11

In [13]:
# Access the element on the first row and the first and second columns

A[0][0:2]

array([11, 12])

In [19]:
# Access the elements on the first and the second rows and the third columns
A[0:2, 2]

array([13, 23])

# Basic Operations

We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoAdd.png" width="500" />

The numpy array is given by <code>X</code> and <code>Y</code>

In [26]:
# create a numpy array X

x=np.array([[1,0],[0,1]])
x

array([[1, 0],
       [0, 1]])

In [28]:
# create a numpy array y

y=np.array([[2,1],[1,2]])
y

array([[2, 1],
       [1, 2]])

In [29]:
# add x and y as follows

z=x+y
z

array([[3, 1],
       [1, 3]])

In [31]:
# multiply y with 2
z= y*2
z

array([[4, 2],
       [2, 4]])

In [32]:
# Create a numpy array y
y=np.array([[2,1],[1,2]])
y

array([[2, 1],
       [1, 2]])

In [33]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [35]:
# Multiply X with Y

Z = x * y
Z

array([[2, 0],
       [0, 2]])

In [36]:
# Matrix Multiplication via the numpy function dot
# create a matrix A
A=np.array([[0,1,1],[1,0,1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [37]:
# Create a matrix B
B=np.array([[1,1],[1,1],[-1,1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [38]:
# calculate the dot product

z=np.dot(A,B)
z

array([[0, 2],
       [0, 2]])

In [39]:
# Calculate the sine of Z
np.sin(z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [40]:
#create a matrix c 

c=np.array([[1,1],[2,2],[3,3]])
c

array([[1, 1],
       [2, 2],
       [3, 3]])

In [42]:
#get the transpose of c
c.T

array([[1, 2, 3],
       [1, 2, 3]])

In [43]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [46]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])